name: workflow for Maven using Snyk security scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --sarif  > results.sarif
        continue-on-error: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
