name: workflow for Maven using Snyk security scan
on: push
jobs:
  security:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Snyk CLI to check for security issues
        # Snyk can be used to break the build when it detects security issues.
        # In this case we want to upload the SAST issues to GitHub Code Scanning
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb      
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
      - name: Snyk Code test
        #run: snyk test --all-projects --org=aef0364d-d779-4277-a254-86c9a1273e6c
        run: snyk code test 
         #snyk code test --sarif > snyk-code.sarif 
        #env:
         #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: snyk-code.sarif
